# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'chronreact' do
  pod 'Batch', '~> 1.5'
end
